### ISSUE TITLE
 Logo Proposal / Icon for MediaLoader

### ISSUE THREAD

**Issue by orlant** [jiajunhui/MediaLoader#1]
a big hello friend, I have noticed that your logo does not have a logo yet, if you allow me I can design a Logo / Icon for your application if it is your total pleasure.

**Comment by jiajunhui** [comment]
Very nice. You can start your work. My friend. If you need to know some repository information, you can ask questions at any time.

**Comment by orlant** [comment]
Thank you very much, in advance I went through your blog where it gives the full description of this android application http://jiajunhui.cn/project_mediaload/#more and found enough information to start my proposal I will return when I have designed something, see you later

**Comment by orlant** [comment]
Good afternoon it's a pleasure to greet you and come back again but this time with the icon designs for your android application. this design each piece has been created for this application and in the same way as this application works that can load images, music, audios and videos. then I will be inspired to represent all these functions in the same logo. Here is the result with 2 different styles.

**Comment by orlant** [comment]
![banners2](https://user-images.githubusercontent.com/40074778/42656974-ebc26a60-85ee-11e8-8958-68f62f0ede41.png)

![banners23](https://user-images.githubusercontent.com/40074778/42657107-4d1d924e-85ef-11e8-9dcb-3501f7e92ea7.png)
![banners3434](https://user-images.githubusercontent.com/40074778/42657139-6cfc29a4-85ef-11e8-8898-301130df260a.png)
![banners](https://user-images.githubusercontent.com/40074778/42657155-74e4f5ba-85ef-11e8-9e37-8260338e0162.png)

**Comment by jiajunhui** [comment]
Sorry, I've been busy working for the last two days. The design is very beautiful. I prefer the first one to the above.
![image](https://user-images.githubusercontent.com/8542947/42719772-ef30e216-874d-11e8-8ebf-b112e999aa60.png)

**Comment by orlant** [comment]
Does he like it? Would he stay with that same one like this? or would it make any change to the text color? to know if I can send you the files PSD, PNG, EPS, SVG, AI

**Comment by jiajunhui** [comment]
I think the color match is pretty good. Very good, no more change of the design.

**Comment by orlant** [comment]
ok very well that you have liked this logo of all those that show you ... now you can close the Issue. I will now upload all the editable files for you.

**Comment by jiajunhui** [comment]
All right, thank you very much.

**Comment by orlant** [comment]
Hello here are the loaded files ready to use if you do not want more. You can download them now. Thanks to you

[FILES MEDIALOADER](https://drive.google.com/open?id=1ZiryTZokFu17yBjcP-l65qthqXAfeGdL)

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.

**Comment by orlant** [comment]
hello friend and send the files please send me an email when it is added to your repository please that good you have liked I am always at your order.
